# Generated by Django 4.2.2 on 2023-06-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Name', models.CharField(max_length=50)),
                ('Cust_Mail', models.CharField(max_length=50)),
                ('Cust_Phone', models.CharField(max_length=10)),
                ('Cust_Pass', models.CharField(max_length=50)),
                ('Cust_House', models.CharField(max_length=50)),
                ('Cust_Road', models.CharField(max_length=50)),
                ('Cust_Locality', models.CharField(max_length=50)),
                ('Cust_Dist', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=50)),
                ('Shop_Mail', models.CharField(max_length=50)),
                ('Shop_Owner_Name', models.CharField(max_length=50)),
                ('Shop_Phone', models.CharField(max_length=10)),
                ('Shop_Pass', models.CharField(max_length=50)),
                ('Shop_Road', models.CharField(max_length=50)),
                ('Shop_Locality', models.CharField(max_length=50)),
                ('Shop_Dist', models.CharField(max_length=50)),
            ],
        ),
    ]
