# Generated by Django 4.2.1 on 2023-06-10 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
