# Generated by Django 4.2.1 on 2023-06-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_bill_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
