# Generated by Django 4.2.1 on 2023-06-10 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Id', models.IntegerField()),
                ('Shop_Id', models.IntegerField()),
                ('Cust_House', models.CharField(max_length=50)),
                ('Cust_Road', models.CharField(max_length=50)),
                ('Cust_Locality', models.CharField(max_length=50)),
                ('Cust_Dist', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Id', models.IntegerField()),
                ('Item_Quantity', models.IntegerField()),
                ('Item_Count', models.IntegerField()),
                ('Item_Price', models.IntegerField()),
            ],
        ),
    ]
