# Generated by Django 4.2.2 on 2023-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Id', models.IntegerField()),
                ('Shop_Id', models.IntegerField()),
                ('Item_Id', models.IntegerField()),
                ('Item_Quantity', models.IntegerField()),
                ('Item_Quantity_Type', models.CharField(max_length=7)),
                ('Item_Price', models.FloatField()),
            ],
        ),
    ]
