# Generated by Django 4.2.2 on 2023-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Item_Count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
