# Generated by Django 4.2.2 on 2023-06-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_cart_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Item_Delivered',
            field=models.CharField(default=12, max_length=1),
            preserve_default=False,
        ),
    ]
