# Generated by Django 4.2.2 on 2023-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_bill_items_item_quantity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_items',
            name='Bill_Id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
