# Generated by Django 4.2.2 on 2023-06-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_bill_items_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Total_Price',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
