# Generated by Django 4.2.2 on 2023-06-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_bill_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Item_Delivered',
        ),
        migrations.AddField(
            model_name='bill',
            name='Item_Delivered',
            field=models.CharField(default=12, max_length=1),
            preserve_default=False,
        ),
    ]
