# Generated by Django 4.2.2 on 2023-06-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_cart_item_delivered_bill_item_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_items',
            name='Item_Name',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
