# Generated by Django 4.2.2 on 2023-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_bill_items_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Id', models.IntegerField()),
                ('Shop_Id', models.IntegerField()),
                ('Satisfaction', models.CharField(max_length=10)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
