# Generated by Django 4.2.2 on 2023-06-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Cust_Name',
            field=models.TextField(default=21),
            preserve_default=False,
        ),
    ]
