# Generated by Django 4.2.2 on 2023-06-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_shop_item_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_Variant',
        ),
    ]
